### ISSUE TITLE
Callback was already called

### ISSUE THREAD

**Issue by DmitryPogodaev** [wavded/winston-mail#22]
I don't know should i open new issue or not. I described problem here https://github.com/wavded/winston-mail/issues/18#issuecomment-89914739
It's just part of already fixed bug, but i still have it after updating module

**Comment by wavded** [comment]
Can you give me a code sample that reproduces the error?

**Comment by DmitryPogodaev** [comment]
Hello, Marc!

In my case you need to setup whole project.

But I think this pseudo would be enought:
```
var arr = [1, 2, 3];
async.eachSeries(arr , function(userId, callback) {
   anySyncFunc(userId);
}, function(err){ 
  return;
});

anySyncFunc = function (userId) {
  return someOtherFunc(userId, function (err) {
    if (err) return logger.log('error', err); 
  });
}

someOtherFunc = function (userId, callback) {
  if (true) callback('Some Error');
}
```

**Comment by wavded** [comment]
This seems related: https://github.com/eleith/emailjs/pull/116  Are you running the latest winston-mail?  It should have emailjs 0.3.13 as a dependency when you do an `npm ls`.  I don't think the issue lies in this library specifically.

**Comment by DmitryPogodaev** [comment]
Oh,  i see you didn't read this comment https://github.com/wavded/winston-mail/issues/18#issuecomment-89914739 

> Just updated with npm update && npm rebuild.
> Current version of winston-mail:
> "version": "0.3.2",
> And emailjs:
> "version": "0.3.13"

npm ls says
```
└─┬ winston-mail@0.3.2
  ├─┬ emailjs@0.3.13
```

**Comment by wavded** [comment]
Hmmm.. I published 0.4.0 with that dep change, that's the most recent one for you?  Maybe I goofed.

**Comment by DmitryPogodaev** [comment]
Oh, Marc, I'm sorry, that's in my package.json. Will update to new 0.4.0 version to fix it.
Thanks for the answers!

**Comment by wavded** [comment]
@DmitryPogodaev sounds good, let me know if you still have problems.

**Comment by endquote** [comment]
I'm still seeing this:

```
var log = require('winston');
var mail = require('winston-mail').Mail;
log.add(log.transports.Mail, {
    to: 'josh@endquote.com'
});

log.level = 'debug';
log.error('foo');
log.error('bar'); // if I remove this line, it doesn't die
```

**Comment by wavded** [comment]
Can I get an output of `npm ls` for winston-mail in your local setup?

**Comment by endquote** [comment]
Sorry, should have included that.

```
Dakuten:test-winston josh$ npm -v
2.9.1
Dakuten:test-winston josh$ node -v
v0.12.3
Dakuten:test-winston josh$ npm list
/Users/josh/Source/test-winston
├─┬ winston@1.0.0
│ ├── async@0.9.2
│ ├── colors@1.0.3
│ ├── cycle@1.0.3
│ ├── eyes@0.1.8
│ ├── isstream@0.1.2
│ ├── pkginfo@0.3.0
│ └── stack-trace@0.0.9
└─┬ winston-mail@0.4.0
  ├─┬ emailjs@0.3.13
  │ ├── bufferjs@1.1.0
  │ ├─┬ mimelib@0.2.14
  │ │ ├── addressparser@0.2.1
  │ │ └─┬ encoding@0.1.11
  │ │   └── iconv-lite@0.4.10
  │ ├── moment@1.7.0
  │ └── starttls@0.2.1
  └── underscore@1.4.4
```

**Comment by wavded** [comment]
@endquote I see your emailjs is out of date (but this package.json is enforcing it).  what if you do:

```
cd node_modules/winston-mail
npm i emailjs@latest -S
```

and try to reproduce, same issue?  if not, i'll update the package.json to the latest version

**Comment by endquote** [comment]
No dice.

```
Dakuten:test-winston josh$ cd node_modules/winston-mail/
Dakuten:winston-mail josh$ npm i emailjs@latest -S
emailjs@0.3.16 node_modules/emailjs
├── bufferjs@1.1.0
├── starttls@0.2.1
├── addressparser@0.3.2
├── moment@1.7.0
└── mimelib@0.2.14 (addressparser@0.2.1, encoding@0.1.11)
Dakuten:winston-mail josh$ cd ../../
Dakuten:test-winston josh$ node foo.js 
/Users/josh/Source/test-winston/node_modules/winston/node_modules/async/lib/async.js:30
            if (called) throw new Error("Callback was already called.");
                              ^
Error: Callback was already called.
    at /Users/josh/Source/test-winston/node_modules/winston/node_modules/async/lib/async.js:30:31
    at /Users/josh/Source/test-winston/node_modules/winston/lib/winston/logger.js:193:9
    at Object.callback (/Users/josh/Source/test-winston/node_modules/winston-mail/lib/winston-mail.js:98:5)
    at connect (/Users/josh/Source/test-winston/node_modules/winston-mail/node_modules/emailjs/smtp/client.js:69:19)
    at caller (/Users/josh/Source/test-winston/node_modules/winston-mail/node_modules/emailjs/smtp/smtp.js:49:14)
    at Socket.response (/Users/josh/Source/test-winston/node_modules/winston-mail/node_modules/emailjs/smtp/smtp.js:139:9)
    at Socket.g (events.js:199:16)
    at Socket.emit (events.js:129:20)
    at net.js:459:14
    at process._tickCallback (node.js:355:11)
```

**Comment by wavded** [comment]
Hmm... well not sure, looks to be an issue upstream, has crept up a couple times for this lib already.

https://github.com/eleith/emailjs/search?utf8=✓&q=callback&type=Issues

Perhaps we need another email backend unless you want to investigate the issue further and see if a fix can be had.

**Comment by endquote** [comment]
It looks like if I add a valid host/username/from/password, there's no issue. Probably emailjs' test cases aren't covering this scenario.

**Comment by endquote** [comment]
Though... the callstack seems to indicate that winston's the last link in the chain there. Maybe emailjs is fine but winston is broke?
