### ISSUE TITLE
Email subject should configureable

### ISSUE THREAD

**Issue by danielschwartz** [wavded/winston-mail#3]
As a developer, in addition to the current properties I should also be able to set what the subject of the mail looks like. It would be easy enough to do with Underscore templates (or any other string replacement engine), it could look like:

subject: "API ERROR: {level} on Web1: {msg}"

Let me know if you would like a pull request for this

**Comment by vipreshjha** [comment]
Any idea if dynamic subject is supported ? as nothing in this regard is mentioned in docs, if it is supported can any one give an example showing how Mail Subject can be set while logging message through email logger.

**Comment by wavded** [comment]
Added; https://github.com/wavded/winston-mail#subject-templating
