### ISSUE TITLE
update dependencies

### ISSUE THREAD

**Issue by japel** [wavded/winston-mail#30]
Hey there!

Would you mind if we update dependencies? Specifically:
emailjs 1.0.0
underscore 1.8.3

I've done so, and tests pass.

**Comment by japel** [comment]
https://github.com/wavded/winston-mail/pull/31

**Comment by wavded** [comment]
Hey @japel, thx for the pull, were there any issues these dependency changes fixed for you?  Mostly curious.

**Comment by japel** [comment]
@wavded oh, no, not really. no issues found. just those typical warnings using node 4.2.2 lts because starttls 0.2.1 wants node 0.x, ... so nothing wrong with the used versions.
But IMO, being able to update to a major release without issues should be seen as a chance :)

**Comment by TylerBrock** [comment]
I'd actually really like it if this was merged as well as an update to starttls so we can avoid these:

`npm WARN engine starttls@0.2.1: wanted: {"node":"0.x"} (current: {"node":"5.0.0","npm":"3.3.6"})`

**Comment by wavded** [comment]
released in `1.0.1`
