### ISSUE TITLE
Transport already attached: console, assign a different name

### ISSUE THREAD

**Issue by oliviergoulet5** [wavded/winston-mail#47]
Not exactly sure what's going on here. I don't know how to remove the existing transport so I can restart the steps. This prevents me of running the bot. I got here from having a syntax error and running node bot.js however after fixing the syntax I cannot repeat the command. 

This error message happens when I type `node bot.js`

**Comment by wavded** [comment]
Can you share `bot.js` or something minimal that illustrates the issue?
