### ISSUE TITLE
Support winston3.0.0

### ISSUE THREAD

**Issue by zhangjinzhou** [wavded/winston-mail#48]
I upgraded winston to 3.0.0. It seems winston-mail is considered legacy. Do we need an update?

**Comment by wavded** [comment]
Support for 3.0 was added in 1.5.0. AFAIK this isn’t a legacy module

**Comment by zhangjinzhou** [comment]
Interesting, I always get this message:
```
mail is a legacy winston transport. Consider upgrading: 
- Upgrade docs: https://github.com/winstonjs/winston/blob/master/UPGRADE-3.0.md
```
when consume log message with winston-mail.
BTW, I am not able to successfully get `message` and `level` in `formatter` option. Maybe these two are both related to some error I made in my code. Here is how do I use the library:
```
const myFormat = printf(options => {
    return options.timestamp + "[x]" + options.level.toUpperCase() + ": " + options.message + "\n";
});
export const logger = winston.createLogger({
    format: combine(timestamp(), myFormat),
    transports: [
        new winston.transports.File ({
            level: "info",
            stream: fs.createWriteStream(config.get<ConfigLog>("Log").directory, {flags: "a"})
        })]
});
const loggerOptions: any = {
    from: "Accounts <gistic.inc@gmail.com>",
    to: config.get<ConfigLog>("Log").receiver,
    username: config.get<ConfigEmail>("Email").user,
    host: config.get<ConfigEmail>("Email").host,
    password: config.get<ConfigEmail>("Email").password,
    level: "error",
    subject: "LBS Error Notification",
    secure: config.get<ConfigEmail>("Email").secure,
    // TODO: current version is not updated to support winston 3.0.0. Therefore options contains undefined values of message and level
    formatter: (options) => { return options.message; }
}

logger.add(new Mail(loggerOptions));
```

**Comment by wavded** [comment]
Hmm, I don't know and do not have the time ATM to investigate. @bcosma worked on the support for 3.0, perhaps he has an idea. If a solution is available, that is backwards compatible with 2.0, I'd be open for PR.

**Comment by jcristovao** [comment]
@bcosma , any news regarding this?
Thanks

**Comment by ericdrobinson** [comment]
Over the past few months I've started receiving empty emails where the `level` wasn't properly set in the Subject field. Today, I finally took the time to attach a debugger and see what's happening. Here's the issue:

At some point in the run-up to final 3.0 release, the Winston team adjusted the Transport setup. Specifically, they changed the way that you import the base Transport class. The new approach is outlined in the [winston-transport](https://github.com/winstonjs/winston-transport) ReadMe:

```js
const Transport = require('winston-transport');
```

This as opposed to the way pre-3.0 approach ([the way `winston-mail` does it](https://github.com/wavded/winston-mail/blob/aab366924de7f33224122c51a7bb69ef57b33047/lib/winston-mail.js#L52)): 

```js
const Transport = require('winston').Transport;
```

[Winston 3.0's Upgrade docs](https://github.com/winstonjs/winston/blob/master/UPGRADE-3.0.md) [specifically mention](https://github.com/winstonjs/winston/blob/master/UPGRADE-3.0.md#transports) that this should be upgraded.

While I haven't confirmed this yet, I suspect that if you connect a `Transport` the **old** way, then the `Transport` class you end up extending _isn't_ the new one, but the new "[Legacy](https://github.com/winstonjs/winston-transport/blob/master/legacy.js)" Transport. My suspicions here are driven by the fact that this is the file I ended up in when debugging. It is _also_ the file that contains the warning showing up in everyone's consoles (as reported by @zhangjinzhou [here](https://github.com/wavded/winston-mail/issues/48#issuecomment-397101568)).

# Probable Fix
Were I a betting man, I'd say that adding `winston-transport` as a dependency and adjusting the way the Transport class is imported to the first version above will fix the issue we're all having with this.

**Comment by ericdrobinson** [comment]
I found where the determination to use the **Legacy** Transport setup comes in. See this snippet [from Logger.js](https://github.com/winstonjs/winston/blob/af941f4c98a24ba9efd7743fdde531903208cda7/lib/winston/logger.js#L270):

```js
// Support backwards compatibility with all existing `winston < 3.x.x`
// transports which meet one of two criteria:
// 1. They inherit from winston.Transport in  < 3.x.x which is NOT a stream.
// 2. They expose a log method which has a length greater than 2 (i.e. more then
//    just `log(info, callback)`.
const target = !isStream(transport) || transport.log.length > 2
    ? new LegacyTransportStream({ transport })
    : transport;
```

It's that second check that appears to cause the issue. The `winston-mail` `Log` function [takes four parameters](https://github.com/wavded/winston-mail/blob/aab366924de7f33224122c51a7bb69ef57b33047/lib/winston-mail.js#L73).

If maintaining backwards compatibility is important, then I would suggest removing `arg2` and `arg3` and access those with the `arguments` Array when necessary.

**Comment by sido420** [comment]
updates? getting those annoying messages

**Comment by ericdrobinson** [comment]
@wavded My tests with the newest version ([1.5.2](https://github.com/wavded/winston-mail/releases/tag/v1.5.2)) show that my emails now properly contain the log level and log message as expected.

As a  result, I would recommend closing this issue.
