### ISSUE TITLE
Peer dependencies issue with winston

### ISSUE THREAD

**Issue by fracchan** [wavded/winston-mail#9]
Hi :)

I just installed the latest version of winston (v. 0.7.2) and proceeded to install winston-mail.
Unfortunately I got the following error messages during installation:
npm ERR! peerinvalid The package winston does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer winston-mail@0.2.5 wants winston@>=0.5.0 <0.7.0

It seems to me that the peer dependencies need to be updated to allow version of winston greater than 0.7.0.
It seems to be working just fine on 0.7.2 otherwise.

Thanks
fracchan

**Comment by jherrerosb** [comment]
NPM is reporting a vulnerability due to the version of emailjs. The version has moment as a dependency and moment version is vulnerable.
